load("//tools/install:install.bzl", "install")
package(
    default_visibility = ["//visibility:public"],
)

install(
    name = "install",
    deps = [
        "//modules/tools/cyber_launch:install",
        "//modules/tools/cyber_recorder:install",
    ],
)

